package com.pedro.test_1.data.repo

import com.pedro.test_1.domain.entities.AuthResult
import com.pedro.test_1.domain.entities.ListItem
import com.pedro.test_1.domain.entities.User
import com.pedro.test_1.data.source.LocalDataSource
import com.pedro.test_1.domain.entities.RepoItems
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import kotlin.math.max
import kotlin.math.min
import kotlin.random.Random

class FakeRepository(private val localDataSource: LocalDataSource) : Repository {
    private val totalItems = 1000

    override suspend fun fetchItems(page: Int, pageSize: Int, query: String?): RepoItems {
        // Ensure caller is authenticated for testing purposes
        val logged = localDataSource.isLoggedIn.first()
        if (!logged) throw IllegalStateException("Not authenticated")

        // Simulate network/disk delay
        delay(150)
        val start = (page-1) * pageSize
        val end = min((start + pageSize).coerceAtMost(totalItems), 150)
        if (start >= end) return RepoItems(data = emptyList(), nextPage = null)

        return RepoItems(
            data = (start until end).map { index ->
                val id = "item-$index"
                val title = if (query.isNullOrBlank()) "Item #$index" else "Item #$index — matches '$query'"
                ListItem(
                    id = id,
                    title = title,
                    subtitle = "Subtitle for item $index",
                    details = "Detailed description for item $index. Random:s ${Random.nextInt(0, 9999)}"
                )
            },
            nextPage = page + 1
        )
    }

    override suspend fun getItemById(id: String): ListItem? {
        val logged = localDataSource.isLoggedIn.first()
        if (!logged) throw IllegalStateException("Not authenticated")

        delay(80)
        return ListItem(
            id = id,
            title = "Detail for $id",
            subtitle = "Subtitle $id",
            details = "Full details for $id — generated by FakeRepository"
        )
    }

    override suspend fun login(username: String, password: String): AuthResult {
        delay(200)
        if (username.isBlank() || password.length < 4) {
            return AuthResult.Failure("Invalid credentials")
        }
        val user = User(id = "u-${username.hashCode()}", name = username, email = "$username@example.com")
        return AuthResult.Success(user)
    }

    // Session-related implementations delegate to LocalDataSource
    override fun isLoggedIn(): Flow<Boolean> = localDataSource.isLoggedIn

    override fun username(): Flow<String?> = localDataSource.username

    override suspend fun saveUser(user: User) = localDataSource.saveUser(user)

    override suspend fun logout() = localDataSource.clear()

    //FAKE REPO FOR TESTING PURPOSES ONLY
}
